name: Тестирование и деплой

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Тестирование
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v3
        
      - name: Настройка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Установка зависимостей
        run: npm ci
        
      - name: Линтинг
        run: npm run lint
        
      - name: Юнит-тесты
        run: npm test
        
      - name: E2E тесты
        uses: cypress-io/github-action@v5
        with:
          build: npm run build:web
          start: npm run start:web
          wait-on: 'http://localhost:3000'
          
      - name: Сохранение скриншотов и видео при ошибке
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            tests/snapshots
            tests/videos
          retention-days: 7

  deploy:
    name: Деплой
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v3
        
      - name: Настройка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Установка зависимостей
        run: npm ci
        
      - name: Сборка
        run: npm run build:web
        
      - name: Деплой на Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          vercel-args: '--prod'
